### ISSUE TITLE
Certbot SSL certificates are missing

### ISSUE THREAD

**Issue by mayur-chavhan** [woosungchoi/docker-wordpress#8]
Error Logs from Nginx, Where it could not able to find SSL certificates.

/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/s1.mydomain.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/s1.mydomain.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by woosungchoi** [comment]
What command did you use?

What is your enviroment?

**Comment by mayur-chavhan** [comment]
#### Issue description

I followed the simple 2 commands in give instructions on my Ubuntu 20.04 host os server on Google Cloud and Port 80 and 443 are open.

- [ ] sudo apt update -y && sudo apt upgrade -y && sudo apt install curl git cron -y && sudo apt autoremove -y

- [ ] curl -o dc https://raw.githubusercontent.com/woosungchoi/docker-wordpress/master/dc && bash dc setup && rm -f dc

for testing i have pointed the test domain to host os : s1.mydomain.com then everything worked fine until nginx container keep getting restarted so i checked the logs using these commands.
 
#### Steps to reproduce the issue

1.  docker ps [ to check containers are working fine or not and found nginx container showing restarting] 
2.  docker logs nginx [ which showed this error 
``` docker
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/s2.mydomain.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:
```
3. I checked SSL folder where this "fullchain.pem" file should exists

#### What's the expected result?

This is folder structure where all docker-compose.yml and wordpress folders 
``` bash
$ ls

README.md  build  build-8.0  data  dc  dcc  dccl  dcl  dcwl  docker-compose.local.yml  docker-compose.ssl.yml  docker-compose.yml  docker_upgrade.sh  nginx  php  site  ssl
```
Where ssl folder should have contain fullchain.pem file which is failed to exists.

In ssl folder list..
``` bash

$ ls ssl
accounts  csr  keys  renewal  renewal-hooks
```
-


#### What's the actual result?

``` bash

docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED             STATUS                          PORTS                NAMES
46e16173803b   nginx:alpine                    "/docker-entrypoint.…"   About an hour ago   Restarting (1) 39 seconds ago                        nginx
cbcfff0ba1fc   phpmyadmin:fpm-alpine           "/docker-entrypoint.…"   About an hour ago   Up About an hour                9000/tcp             phpmyadmin
198838912f29   wordpress_php                   "docker-entrypoint.s…"   About an hour ago   Up About an hour                9000/tcp             php
d27de83f3955   redis:alpine                    "docker-entrypoint.s…"   About an hour ago   Up About an hour                6379/tcp             redis
049347d98074   mariadb:latest                  "docker-entrypoint.s…"   About an hour ago   Up About an hour                3306/tcp             db

```
So Certbot is suppose to create certificates and put those certificates on SSL folder.

SSL folder is later mounted by nginx container on /etc/letsencrypt path 

nginx vhost is not able to find the file so container keep getting restarted.

What am i missing ?

**Comment by woosungchoi** [comment]
Thanks to you in detail, I understand what's wrong. In short, to use SSL, the domain must point to the correct IP. So, for the test domain, the problem is that Nginx cannot find the certificate because the SSL certificate is not issued. To fix this problem, you must use a valid domain. You can get a free domain for testing at http://www.freenom.com.

**Comment by mayur-chavhan** [comment]
i'm not using s1."mydomain".com as a domain for testing, I can afford to buy a domain just for testing which is already at Cloudflare but for security reason i can't share exact domain here. 

I know already that Certbot can't able to generate SSL but i have mounted the "/etc/letsencrypt" folder but it won't show proper folder structure where it supposed to show live folder etc.

So i have found that certbot also has separate image for Cloudflare and tested with that so now i have fixed my problem, so i would like to share the code.

Create cloudflare.ini file 

``` bash
dns_cloudflare_email = YOUR@EMAIL.COM
dns_cloudflare_api_key = XXXXXXXXXXXXXXXXXXXX
```


``` Dockerfile
....
  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cloudflare.ini:/root/cloudflare.ini
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --email myemail@gmail.com
      --agree-tos --no-eff-email
      --force-renewal
      -d s1.mydomain.com
      -d s2.mydomain.com
      -d anotherdomain.com

    nginx:
    depends_on:
      - php
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - phpmyadmin:/var/www/html
      - certbot_etc:/etc/letsencrypt/
      - ./site:/var/www/web
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx/
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  certbot_etc:
  phpmyadmin:

```
But drawbacks on this is that i have to use my cloudflare API keys which are not secure way just for SSL so need to ask if you have any other method where we can certbot for generating SSL ?

Thanks in Advance.

**Comment by woosungchoi** [comment]
Oh, I see. 

In this script, it is written so that only specific 4 domains are issued SSL certificates.

For example,

```
certbot    | http-01 challenge for caps.ml
certbot    | http-01 challenge for pma.caps.ml
certbot    | http-01 challenge for port.caps.ml
certbot    | http-01 challenge for www.caps.ml
```

If you look at the process of obtaining an SSL certificate, you can see that it is issued as above.

So, if you want a specific subdomain, you have to modify the script yourself.

https://github.com/woosungchoi/docker-wordpress/blob/master/docker-compose.yml#L11

If you look at the line above, you can see in which subdomain Certbot receives SSL certificates.

You can fork this repository and modify the script to use it.

**Comment by mayur-chavhan** [comment]
@woosungchoi Thank you very much. That solved the issue.
